openapi: 3.0.3

info:

components:
  responses:
    NoContent:
      description: No Content
    BadRequest:
      description: Bad Request
    NotFound:
      description: Not Found
    Created:
      description: Created
    ServerError:
      description: Unexpected error
    OK:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas.yaml#/components/schemas/RecipeResponse'