openapi: 3.0.3

info:
  version: 1.0
  title: Schema
paths:

components:
  schemas:
    RecipeRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        title:
          type: string
        dishType:
          $ref: "#/components/schemas/DishType"
        servings:
          type: integer
        ingredients:
          type: array
          items:
            type: string
          example: ["spaghetti", "garlic", "olive oil"]
        instructions:
          type: string
          example: "1. Cook spaghetti\n2. Heat olive oil and garlic in a pan\n3. Add red pepper flakes\n4. Toss cooked spaghetti in the pan\n5. Serve hot"
    RecipeResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        title:
          type: string
        dishType:
          $ref: "#/components/schemas/DishType"
        servings:
          type: integer
        ingredients:
          type: array
          items:
            type: string
          example: [ "spaghetti", "garlic", "olive oil" ]
        instructions:
          type: string
          example: "Cook spaghetti. Heat olive oil and garlic in a pan. Add red pepper flakes. Toss cooked spaghetti in the pan. Serve hot"
    DishType:
      type: string
      description: "Type of dish"
      example: "VEGETARIAN"
      enum:
        - VEGETARIAN
        - NON_VEGETARIAN